FROM gruz0/burn_my_fat:0.2
MAINTAINER Alexander Kadyrov <gruz0.mail@gmail.com>

ENV HANAMI_ENV=test

WORKDIR /app
COPY . /app
RUN bundle install -j $(nproc) --quiet --without production

CMD ["bin/test.sh"]
